#include <stdlib.h>
#include <stdio.h>
int main(int argc, char **argv){

     int H2 = atoi(argv[1]);
     int Vitamin_K = atoi(argv[2]);
     int Hematin = atoi(argv[3]);
     int Glucose = atoi(argv[4]);
     int Acetate = atoi(argv[5]);
     int Formate = atoi(argv[6]);
     int B12 = atoi(argv[7]);
     /* printf("H2 %d, Vitamin_K %d, Hematin %d, Glucose %d, Acetate %d, Formate %d, B12 %d\n", */
     /* 	    H2,Vitamin_K,Hematin,Glucose,Acetate,Formate,B12); */
     
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("A\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("C\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("D\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("E\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("F\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("H\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("I\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("J\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("K\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("L\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("M\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("A\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("L\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("F\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("H\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("F\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("H\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("A\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("C\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("N\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("M\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("L\n");
     if (H2==0 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("I\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("J\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("F\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("J\n");
     if (H2==0 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("D\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("M\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("E\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("K\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("L\n");
     if (H2==0 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("B\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("F\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("J\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("F\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("G\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("J\n");
     if (H2==0 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("K\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("C\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("A\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("E\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("I\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("J\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("I\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("J\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("N\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("M\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("L\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("K\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("E\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==0) printf("I\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==0) printf("J\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==0) printf("F\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==0) printf("H\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==0) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("D\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("C\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("A\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("E\n");
     if (H2==1 && Vitamin_K==0 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("I\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("H\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("I\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("J\n");
     if (H2==1 && Vitamin_K==0 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("A\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("E\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("N\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("E\n");
     if (H2==1 && Vitamin_K==1 && Hematin==0 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("B\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==0 && B12==1) printf("F\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==0 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==0 && B12==1) printf("J\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==0 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==0 && Formate==1 && B12==1) printf("F\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==0 && Formate==1 && B12==1) printf("G\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==0 && Acetate==1 && Formate==1 && B12==1) printf("J\n");
     if (H2==1 && Vitamin_K==1 && Hematin==1 && Glucose==1 && Acetate==1 && Formate==1 && B12==1) printf("G\n");

     return 0;
}
  

