#!/usr/bin/env python

"""
This is a run_script example that run a program call "prog.exe" 

take in as input a list of varname and value and and return in stdout (the terminal screen) a list of covered lines

e.g.,
./testscript "x 0, y 1, z 0"   #this represent the configuration x = 0 , y = 1 z = 0
l3
l4
l7

"""
import os.path
import subprocess as sp

def iread(filename):
    """ return a generator """
    with open(filename, 'r') as fh:
        for line in fh:
            yield line

def iread_strip(filename):
    """
    like iread but also strip out comments and empty line
    """
    lines = (l.strip() for l in iread(filename))
    lines = (l for l in lines if l and not l.startswith('#'))
    return lines


def vcmd(cmd, inp=None, shell=True):
    proc = sp.Popen(cmd,shell=shell,stdin=sp.PIPE,stdout=sp.PIPE,stderr=sp.PIPE)
    return proc.communicate(input=inp)


if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser()

    parser.add_argument("inputs", help="input configurations")

    args = parser.parse_args()
    inputs = args.inputs.strip()  #  "x 0, y 1, z 0"
    parts = [p.split() for p in inputs.split(",")]
    varnames,varvals = zip(*parts)
    assert len(varnames) == len(varvals)

    prog = os.path.abspath("prog.exe")  
    prog_inp = ' '.join(varvals) #"0 1 0"
    prog_out = "/var/tmp/tvn.out"
    cmd = "{} {} > {}".format(prog,prog_inp,prog_out)
    try:
        _,rs_err = vcmd(cmd)
        assert len(rs_err) == 0, rs_err
    except:
        print("cmd '{}' failed".format(cmd))

    print '\n'.join(iread_strip(prog_out))
    

   
